site_name: AOSP and KERNEL Building, Compiling and Flashing 
theme:
  icon:
    logo: fontawesome/solid/shield
  favicon: android.svg
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  font:
    text: Lora
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: cyan 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: lime
  
  plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
    


  
extra:
  #footer-note: Made with :octicons-heart-fill-24:{ .mdx-heart } by the Ilaveni Ranjith.
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/IlaveniRanjith
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/IlaveniRanjith?t=RxkThMbzUZcAb6Wxc_VSTg&s=09
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ranjith-ilaveni-8386a6179
      

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
      &copy: 2023 <a href="https://github.com/IlaveniRanjith"  target="_blank" rel="noopener">Ilaveni Ranjith</a>
# &copy: 2023 <a href="https://github.com/IlaveniRanjith"  target="_blank" rel="noopener">CDAC Hyderabad</a>

